db:
  host: "![zGm5FN28Srb2vUZlNJs9aIoUSGmCDUnj2QCpXvuF6ptJqpVk6d9fBUMZZUIOl/BcCld0kOP8UVx74a4JDa83Rg==]"
  port: "![QYrfFv0ty94=]"
  username: "![5PU8M7Oxi+M=]"
  password: "![7t11+TIZsZjXX27LbHs8Ag==]"
  database: "![qVK0MgH5iwVAYBoG3lp03Q==]"